### ISSUE TITLE
Staff chat hide command isnt working properly

### ISSUE THREAD

**Issue by IasonKalaitzakis** [RefracDevelopment/SimpleStaffChat#33] opened 2024-05-13 00:06 UTC
Tried hiding my admin chat, it wasnt hiding it from my chat.

**Comment by Refrac** [comment] 2024-05-13 00:09
I'm going to need more information than that such as screenshots of you using the command etc.

**Comment by IasonKalaitzakis** [comment] 2024-05-13 20:17
![2024-05-13_23-14-59](https://github.com/RefracDevelopment/SimpleStaffChat/assets/31860283/0b6538cf-a18e-437e-8879-1ab7c175f1af)
![java_2024-05-13_23-15-13](https://github.com/RefracDevelopment/SimpleStaffChat/assets/31860283/41c7554b-304c-4df4-b8ee-1fa64d173a39)
![java_2024-05-13_23-15-26](https://github.com/RefracDevelopment/SimpleStaffChat/assets/31860283/dd09cdcc-04c9-44d2-9b15-8593025abab7)

Paper Version 1.20.4 496
Also using essentialsx and essentialsxchat (not sure if that has any relevance)

**Comment by Refrac** [comment] 2024-05-13 20:23
Alright thanks, i'll look into this

**Comment by Refrac** [comment] 2024-05-15 20:41
@IasonKalaitzakis Alright i found the cause of this issue will be fixed in 4.3.0. 

What happened is i switched the way i was sending staff chat messages to a broadcast system that didn't support the hide command i have decided to revert this change so it should work in 4.3.0 when it is released.

**Closed by Refrac** 2024-05-15 20:41 UTC
Labels: bug

**Comment by IasonKalaitzakis** [comment] 2024-05-16 13:42
Gotcha thanks for the quick fix!
